---
- name: extract installer
  unarchive:
    src: https://download.nextcloud.com/server/releases/latest-12.tar.bz2
    dest: /var/www/html/
    remote_src: True
    owner: apache
    group: apache
  creates: /var/www/html/nextcloud

- name: Create Data Directory
  file:
    dest: /var/www/html/nextcloud/data
    owner: apache
    group: apache
    mode: 0775
    state: directory

- name: Create NextCloud database
  mysql_db:
    name: nextcloud
    state: present

- name: Create NextCloud database user
  mysql_user:
    name: ncuser
    password: pass1234
    priv: nextcloud.*:ALL
    host: localhost
    state: present
