---
- name: install EPEL repo
  yum:
    name: epel-release
    state: present
  when: ansible_distribution == "CentOS"
  
 - name: install EPEL repo (RedHat)
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
  when: ansible_distribution == "RedHat"

- name: install tools
  yum:
    name: '{{ item }}'
    state: latest
  with_items:
    - unzip
    - wget
    - bzip2

- name: Set SELinux to permissive
  selinux:
    policy: targeted
    state: permissive
